### PR TITLE
Fix invalid file paths causing unexpected behavior

### PR DESCRIPTION
**Pull request by in1tiate**
Before the layer refactor, invalid images would display a null pixmap. This restores that behavior.

### CODE REVIEW

**Comment by TrickyLeifa** [comment]
If you want to display null pixmap, do a check in the appropriate part where you need it to display. Don't modify AnimationLoader that already knows how to deal with non-existing files.

**Comment by TrickyLeifa** [comment]
Where is the null pixmap required?

**Comment by TrickyLeifa** [comment]
What exactly required the null pixmap to function properly?

**Comment by in1tiate** [comment]
Per outside discussion, rewrote this to simply hide the offending layer instead of loading a null pixmap.

**Review by TrickyLeifa — APPROVED** [review]

**Pull request merged**
