### PR TITLE
[Feature] Courtroom slide transitions

### PR DESCRIPTION
**Pull request by in1tiate**
Refactor of https://github.com/AttorneyOnline/AO2-Client/pull/869, now with 70% fewer merge conflicts.

Took the old code verbatim and added pair support,. As far as my testing shows, this kinda just works.

Formatting required for setup:

Full courtroom image (should be named "court.png" but can work with any name)
Design.ini parameters:
```
[court:def]
pos_center=320
slide_ms_pro=550
slide_ms_wit=500

[court:wit]
pos_center=1467
slide_ms_pro=500
slide_ms_def=500

[court:pro]
pos_center=2614
slide_ms_def=550
slide_ms_wit=500
```
where "court:pos" is the main image and the name of its subposition.
`pos_center` is the pixel position of the center of the part of the image you want to be a position
and the transition duration settings are formatted as `slide_ms_pos` and a duration in milliseconds.

Additionally, there is support for giving characters a special pose during transitions if an "Objection!" shout was used.
```
[Options]
objection_pose = pointing
```

This PR also adds a checkbox to the main UI to enable or disable sending the new MS parameter `SLIDE` which dictates whether a message is able to trigger a slide animation.

Additionally, a global setting is now in the settings menu to disable slide animations for yourself.

### CODE REVIEW

**Review by Salanto — DISMISSED** [review]
tenor

**Comment by Salanto** [comment]
You may still want to wait for someone else to review this too cause that looks a bit too large for single approval.

**Comment by in1tiate** [comment]
experiencing a bizarre frame effects bug, will check on it tomorrow

**Comment by in1tiate** [comment]
image
ah. Stand by

**Comment by in1tiate** [comment]
Closing, rebased manually on a different branch, see https://github.com/AttorneyOnline/AO2-Client/pull/966

**Pull request closed without merging**
