### PR TITLE
add BB packet for a MessageBox popup

### PR DESCRIPTION
**Pull request by stonedDiscord**
implements #315

### CODE REVIEW

**Comment by newaccountnewlife** [comment]
Looks great so far.``

**Review by oldmud0 — CHANGES_REQUESTED** [review]
Needs a 2 second timer - otherwise the modal dialog can be accidentally closed and never read while the player is typing and spacebar is pressed.

**Review by oldmud0 — CHANGES_REQUESTED** [review]
failing build... try `#include <functional>`

**Review by oldmud0 — APPROVED** [review]
LGTM

**Pull request merged**
