### PR TITLE
Suppress application volume when alt-tabbed

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Add a "suppress_audio" slider setting, 50% by default, which decides how much audio remains when the client is not in focus
Add a "muted" setting for blip, music, and sfx players
Add update_audio_volume func

Closes https://github.com/AttorneyOnline/AO2-Client/issues/693

### CODE REVIEW

**Review by in1tiate — DISMISSED** [review]
This doesn't need to be user-configurable down to the amount of suppression, the slider adds too much settings clutter. Set a fixed value, and have three settings: no suppression, partial suppression, and mute.

**Comment by Crystalwarrior** [comment]
> This doesn't need to be user-configurable down to the amount of suppression, the slider adds too much settings clutter. Set a fixed value, and have three settings: no suppression, partial suppression, and mute.

Uh actually I've been requested by Wiso to add sliders for fine tuning individual audio channels rather than a master Suppression slider, so it's definitely not clutter when there's people who will find those options useful.

There's never a scenario where more options is bad. The user interface behind the settings screen is a separate issue.

**Comment by stonedDiscord** [comment]
Windows has something similiar for all sounds during voice calls.
They used a tab in the sound settings and give your 3 options: off, 50% or 80%
i think the slider uses less space and gives the user more options so i am for it.

**Review by Salanto — APPROVED** [review]
I can get why percent based decreasing is used, even if it causes the decrease to become less pronounced the closer we get to 0., Simple subtraction may have worked too, but since this mimics what WIndows does it's fine.

**Pull request merged**
