### PR TITLE
Fix bad OTF rendering on Windows; load fonts in base/fonts

### LINKED ISSUE #224: [Bug 2.8.4] OTF-format fonts are incorrectly handled by themes
I'm attempting to use OpenType format (.OTF) fonts in a chatbox theme named `misc/ajhd`. Pictured below are `misc/ajhd/courtroom_fonts.ini` and the result of that configuration in the viewport.

unknown-dBxslIn

[Here](https://user-images.githubusercontent.com/32779090/89111798-aa08ce80-d41f-11ea-918e-acb897270ac8.png) is an image depicting an otherwise identical configuration that instead utilizes a TrueType format (.TTF) font.

Changing the value of `message_font` to the file name of the font in question [causes it to be displayed, though with incorrect character positioning and kerning](https://user-images.githubusercontent.com/32779090/89111818-eb00e300-d41f-11ea-9ed8-9991faad8d6e.png). The same is not true for `showname_font`, which staunchly refuses to use OpenType fonts.

All of the above also applies to proper themes (located in `base/themes`) as well, confirmed via my own tests.

I've attached the two offending fonts as well as a copy of `misc/ajhd` for your perusal.

**Attachment: [ajhd.zip](https://github.com/AttorneyOnline/AO2-Client/files/5011384/ajhd.zip)**

### PR DESCRIPTION
**Pull request by oldmud0**
Force the Direct2D QPA on Windows and additionally load fonts from `base/fonts` on startup.

Fixes #224.

### CODE REVIEW

**Review by Crystalwarrior — CHANGES_REQUESTED** [review]
Crashes on startup for me

**Review by in1tiate — CHANGES_REQUESTED** [review]
image

**Comment by oldmud0** [comment]
This is what happens when you try to work on a Windows fix on Linux

**Comment by Crystalwarrior** [comment]
> 
> 
> This is what happens when I try to work on a Windows fix on Linux
> 
> Also you need `platforms/qdirect2d.dll`
> 
> And I need the startup crash stack trace, please.

I put in qdirect2d.dll in platforms/, still crashes. Here's stack trace
https://cdn.discordapp.com/attachments/323377366997008394/810073860635361290/ao2_longbte.tasks
image
image

**Comment by oldmud0** [comment]
Can't reproduce, works for me (windows 7 x64).

**Comment by Crystalwarrior** [comment]
image
:/

**Comment by Crystalwarrior** [comment]
Direct2D is just bad news. Anything to do with how pixmap is handled on current AO2 is completely and utterly busted on win10 of this branch.

**Comment by Crystalwarrior** [comment]
Closing due to platform incompatibilities, we cannot afford to debug this so close to release

**Comment by oldmud0** [comment]
Press f to pay some respeccs

**Pull request closed without merging**
