### PR TITLE
Allow user to remove favorites via context menu

### PR DESCRIPTION
**Pull request by in1tiate**

### CODE REVIEW

**Review by oldmud0 — CHANGES_REQUESTED** [review]
going through some old PRs.

I really think that we should reuse the "add to favorites" button, replacing it instead with a "delete" button when the favorites pane is opened. I made a button image for this and posted it on Discord but I can't find it now.

edit: found it 
image

**Comment by Crystalwarrior** [comment]
Any progress on this?

**Comment by oldmud0** [comment]
honestly let's just use the context menu solution and leave the "add to fav" button as it is for adding servers by IP

**Comment by stonedDiscord** [comment]
context menu doesn't open

add to list does nothing in serverlist

**Comment by Salanto** [comment]
Code is stale and changes to the method mean this entire thing has to be redone. Closing for sake of organisation while a new one is written.

**Pull request closed without merging**
