### PR TITLE
Kfo ao2

### PR DESCRIPTION
**Pull request by stonedDiscord**
release is tomorrow and i see merge conflicts

### CODE REVIEW

**Comment by stonedDiscord** [comment]
it's only 3 files tho

**Comment by oldmud0** [comment]
"only"

**Comment by oldmud0** [comment]
Assuming no last-minute issues arise, here's what will happen in version control:

- `kfo-ao2` is merged cleanly with `master` as a merge commit. (This makes it easy to roll back.)
- The tag `2.8.4` is applied to the head of `master`.
- The `kfo-ao2` branch is deleted.
- The `2.8` branch is created as a maintenance branch, branching off the `2.8.4` tag.

**Comment by stonedDiscord** [comment]
The defense is ready, your honor. 🔨

**Pull request merged**
