### PR TITLE
implement UTF-8 support for evidence saving

### PR DESCRIPTION
**Pull request by Lernos**

### CODE REVIEW

**Comment by Lernos** [comment]
Heh, the run failed here, but went through fine on my fork, already tested and it works. Must've been a hiccup.

**Comment by Salanto** [comment]
Clang tidy had a stroke, which is normal given this branch does not have the recent CI changes.

**Review by oldmud0 — APPROVED** [review]
Clang tidy plugin can shove it for now.

**Comment by oldmud0** [comment]
@Lernos just realized this is on the wrong branch, you need to merge against master

**Comment by Lernos** [comment]
@oldmud0 Oh, I see. Sorry, didn't know that. Well, is there a point in opening another pull anymore for this specific feature? I'd guess not.

**Pull request merged**
