### PR TITLE
Change FL variable names for clarity

### PR DESCRIPTION
**Pull request by in1tiate**
While working on an independent project, I noted that AOApplication contains both a public member `effects_enabled` and a public method `is_effects_enabled`, where the former refers to server support and the latter refers to user preference. This is fairly confusing and should probably change.

### CODE REVIEW

**Comment by in1tiate** [comment]
just going to turn the fucking bot off

**Review by Salanto — APPROVED** [review]

**Review by Salanto — DISMISSED** [review]
Increases contexual clarity a lot.  Also bot gone 🦀

**Review by Salanto — APPROVED** [review]
If I have to approve this one more time I will murder somebody.

**Review by stonedDiscord — APPROVED** [review]
refactor moment

**Review by oldmud0 — COMMENTED** [review]
This refactor is fine, I would have approved it.

**Pull request merged**
