### PR TITLE
WIP: Courtroom transitions (HEAVY CLEANUP REQUIRED)

### PR DESCRIPTION
**Pull request by in1tiate**
I wrote this for a personal project that will never see completion. It is fully functional but I had to remove a not-insignificant amount of existing functionality to make it work. The pair character has been repurposed. It also requires configuration to work properly. I will answer any questions posed to me about how exactly this works.

Here's what it looks like.
https://user-images.githubusercontent.com/32779090/192168204-abde05ee-9309-4e4f-84f1-bca2e48829f5.mp4

### CODE REVIEW

**Comment by Iamgoofball** [comment]
question:
does this function by having 1 really long courtroom /png background icon that we pan between spots on, or does it automatically generate the camera smear frames?

**Comment by in1tiate** [comment]
> question: does this function by having 1 really long courtroom /png background icon that we pan between spots on, or does it automatically generate the camera smear frames?

The former. Automatic generation of the smear frames proved too complex a solution.

**Comment by Iamgoofball** [comment]
it's possible to autogenerate it but i think what we'd want to do is autogenerate the smear frames ahead of time with a tool instead of trying to do it real time with the client

**Comment by Salanto** [comment]
Going to put this in the 2.11 backlog for now. Given that we already redo a lot, read ALL, of courtrooms core design, an addition like this might give a client that is currently purely reworked a little bit more spice.

**Comment by in1tiate** [comment]
Closing. If I'm going to add this upstream it will need to be cherry-picked, and this branch is active again.

**Pull request closed without merging**
