### PR TITLE
Qt6

### PR DESCRIPTION
**Pull request by stonedDiscord**
turns out it didn't take much

depends on #818

### CODE REVIEW

**Comment by stonedDiscord** [comment]
as you can see on this history, Qt6 CI is very difficult to do, so it's not included

**Comment by stonedDiscord** [comment]
most of this
- removes the deprecated setCodec for text files
- replaces the deprecated regex
- fixes up enterevent

**Comment by oldmud0** [comment]
can you add 6.0 to the build matrix to verify the branch works?

**Comment by stonedDiscord** [comment]
No i can't, the tooling isn't able to install the needed Qt6 websockets addon

**Review by Salanto — APPROVED** [review]
LGTM, about Qt6 support, it will be a question of when Linux pulls up the version, but in theory it suffices when the obvious ones are taken care of, imo.

**Pull request merged**
