### PR TITLE
Sort categories ascending instead of leaving them in loaded order

### PR DESCRIPTION
**Pull request by in1tiate**

### CODE REVIEW

**Comment by Salanto** [comment]
Is this even desired behaviour? A lot of servers prefer their sorting of the charlist.

**Comment by in1tiate** [comment]
> Is this even desired behaviour? A lot of servers prefer their sorting of the charlist.

It's _predictable_ behavior. The current behavior is kind of weird and nonsensical unless you know the sort happens in load order.

**Comment by Salanto** [comment]
Can we turn it into a setting :trollface: ?

**Review by Salanto — APPROVED** [review]
Cool and good.

**Pull request merged**
