### PR TITLE
Making the ban message actually intimidating.

### PR DESCRIPTION
**Pull request by JayFaraday**
Ban messages should leave the user with fear and regret, for they have been naughty. The current ban message is too PC; using this one would substantially improve ban effectiveness.

image

### CODE REVIEW

**Comment by in1tiate** [comment]
what

**Comment by JayFaraday** [comment]
> what
I don't understand the confusion; I explained it perfectly. Ban messages shouldn't be all frickin' PC and bureaucratic and "Sorry hon, you got banned, better luck next time." It needs to strike fear into the hearts of these children. Make them never forget.

**Comment by in1tiate** [comment]
> 
> 
> > what
> 
> I don't understand the confusion; I explained it perfectly. Ban messages shouldn't be all frickin' PC and bureaucratic and "Sorry hon, you got banned, better luck next time." It needs to strike fear into the hearts of these children. Make them never forget.

`what`

**Comment by headshot2017** [comment]
emoji

**Comment by caleb-mabry** [comment]
Hm. It looks like that packet isn't supported. Should you want this feature to be implemented, you will need to update all of the servers that rely on this.

Thank you and have a nice day.

**Comment by JayFaraday** [comment]
Okay so apparently I'm an idiot but that shouldn't play a factor in anything

**Comment by oldmud0** [comment]
Qt and QtApng have already been dissed in the entire making of AO, thus the libs have already been owned and there is no need for this PR.

**Pull request closed without merging**
