### PR TITLE
self explanatory

### PR DESCRIPTION
**Pull request by raidensnake**

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Provide an actual reason for us to remove you from the credits. The behavior of this account is seeming like it was hijacked, with the fact you closed multiple PRs you were actively working on, and this odd request to remove yourself from the credits. Closing and contacting github support.

**Comment by Iamgoofball** [comment]
Additionally, this wouldn't fully remove you from the credits as-is since you still have commits in our repository under your account name and email, which we will not be removing as it would mess up the commit logs for anyone with a copy of the repository checked out.

**Comment by raidensnake** [comment]
all I'll say is certain people don't want me being involved anymore...

**Comment by Iamgoofball** [comment]
That is insufficient reason to tamper with the project's credits at this time, especially considering the potential that your account may be hijacked and is under control by a malicious unauthorized user. I will keep this pull request closed until I hear back from Github Support.

**Comment by raidensnake** [comment]
That's not the case. I'm asking for this to be done because I'm not willing to be involved in a project that allows abuse, doxxing and constant harassment by others associated with them.

**Comment by oldmud0** [comment]
> Additionally, the fact that you have changed the supposed reasoning for this pull request so drastically is yet another sign that the raidensnake Github account was clearly hijacked by a malicious third party, and I sincerely hope Github Support restores it to its original owner ASAP. One does not simply switch reasons from "some people don't want me involved with the project anymore" to "THIS PROJECT IS ENGAGING IN DOXXING" like that.

I don't think this is a hijacked account.

> That's not the case. I'm asking for this to be done because I'm not willing to be involved in a project that allows abuse, doxxing and constant harassment by others linked to it. I can even name 2 instances I've had to deal with in less than one year.

I understand that there are other offshoot communities that have caused you harassment in the past, and there are some contributors to this open-source project that have some extent of affiliation with those communities. If you feel threatened or unwelcome in this community (i.e. the main, vanilla, open-source project), please let me know. Maintaining the project's health is my responsibility. However, I am simultaneously concerned about recent erratic behavior regarding some perfectly valid issues and pull requests you had open. I couldn't possibly guess what could be happening on your side.

**Comment by Iamgoofball** [comment]
Account seems to have self-deleted. That pretty much confirms a hijacker trying to cover their tracks.

**Comment by oldmud0** [comment]
I do not see evidence that this behavior is being caused by anyone but the real owner of the account. It has been a few days and I have not been told by any alternate account that their "real" account is being hijacked, that they still want to contribute, etc. This seems to be an attempt by raidensnake to aggressively erase his involvement from the project, though throwing a self-destructive fit and blaming those around him in the process doesn't seem to be a very productive thing to do either.

**Comment by Iamgoofball** [comment]
Well, in light of this information, we should probably pre-emptively ban the raidensnake account that mysteriously got created a few seconds after the original raidensnake account self-deleted, since github support does not work that fast and I still haven't gotten a reply email from github support.

**Comment by Iamgoofball** [comment]
Just received confirmation fron github support that they're looking into the incident.

**Comment by Nahyuta** [comment]
if you say they are as bad as you mentioned then this should be merged.

**Comment by oldmud0** [comment]
To raidensnake: If you still want this to happen, I'm open through the usual channels of communication.

**Pull request closed without merging**
