### PR TITLE
Added apng support for animated background positioning. Also Fix bassopus path for MacOS X.

### PR DESCRIPTION
**Pull request by raidensnake**
fixes https://github.com/AttorneyOnline/AO2-Client/issues/182

### CODE REVIEW

**Comment by raidensnake** [comment]
the main image suffix only handles characters and backgrounds for rendering. The commit addresses apngs not being listed for the positioning since it's tied to that.

**Comment by raidensnake** [comment]
Since one of the background has apngs for it's positions the static code it what dictates the positions listed. if apng isn't added it won't list them whatsoever as it only lists png files.

**Comment by oldmud0** [comment]
Then we switch the change the background loader to use the main image suffix instead of the static image suffix. Right?

**Comment by raidensnake** [comment]
@oldmud0 @Crystalwarrior I managed to figure it out. I hope the change is acceptable.

**Comment by oldmud0** [comment]
I think that should work. Is it tested?

**Comment by raidensnake** [comment]
yes I confirmed it works here.

**Comment by raidensnake** [comment]
Oops. For some reason it added the macos audio fix by mistake as well as I was going to submit it as a seperate pr. Just for the record the fix is confirmed by both Pres on Mac OSX Catalina and ManaMerci on Mac OSX Mojave as well as myself using my macpanda (Lattepanda Alpha Mac OSX High Sierra.)

**Comment by raidensnake** [comment]
@oldmud0 @Crystalwarrior Sorry about this... I didn't think github was gonna pull this stunt on me.

**Pull request merged**
