### PR TITLE
Make "Play Random Song" only select from songs in expanded categories

### PR DESCRIPTION
**Pull request by in1tiate**

### CODE REVIEW

**Review by oldmud0 — APPROVED** [review]
This seems unintuitive, though I'm sure players will figure it out... eventually.

**Comment by oldmud0** [comment]
Why not make the Random Song pool be based on tracks selected with ctrl+click?

**Comment by Crystalwarrior** [comment]
@oldmud0 seems beyond the scope of this particular PR

**Review by Crystalwarrior — APPROVED** [review]

**Comment by oldmud0** [comment]
> @oldmud0 seems beyond the scope of this particular PR

Same functionality, but more intuitive UX.

**Pull request merged**
