### PR TITLE
W.I.P Working objections

### PR DESCRIPTION
**Pull request by cents02**
Changelog for the 4th time because github keeps discarding my PRs:
Added custom objection system. Put a subfolder called "custom_objections" in a chars file and put whatever you want as long as gif name = audio file name.

added /clearooc

Made it so play_sfx to look automatically for supported files and play them. (so no more + ".wav").

Note: this is w.i.p until all bugs/requests are taken care of.

### CODE REVIEW

**Comment by oldmud0** [comment]
Please stop making pull requests for the same set of changes.

**Comment by stonedDiscord** [comment]
custom objections are already in

**Comment by stonedDiscord** [comment]
i misunderstood what this did
this is for the context menu on the custom objection button to have multiple of them

**Comment by oldmud0** [comment]
Isn't this superseded by KFO's custom objection feature? Supposedly there is a client that allows not only one custom objection, but multiple named custom objections in the context menu.

**Comment by cents02** [comment]
I made this feature last year @oldmud0 but you rejected it because you didn't like how I sent the packets of the custom objections as `4&custom_objname`

**Pull request closed without merging**
