### PR TITLE
Make Spectator Character Select Screen button actually function

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Don't hide spectator button anymore
Make the spectator button properly send the char switch packet
Fix the spectator button not properly loading the courtroom and music list etc.

Fixes https://github.com/AttorneyOnline/AO2-Client/issues/114

### CODE REVIEW

**Comment by oldmud0** [comment]
does tsuserver understand

**Comment by Crystalwarrior** [comment]
> 
> 
> does tsuserver understand

I made it understand for KFO, otherwise it needs to be added to the 2.8 compatibility PR
also fixes https://github.com/AttorneyOnline/AO2-Client/issues/114

**Comment by Crystalwarrior** [comment]
@oldmud0 These two commits are relevant to implementing spectator support, can be cherrypicked on tsu3 side: https://github.com/Crystalwarrior/KFO-Server/commit/61336d4829ac427dcd8944a575a3fc772d02b6bb https://github.com/Crystalwarrior/KFO-Server/commit/7820d39039810e95f88778c96073f405fc7167d3

**Comment by oldmud0** [comment]
i feel like this has some implications i don't fully understand yet, since I'm not sure if all functions check for the `-1` case

**Comment by Crystalwarrior** [comment]
> 
> 
> i feel like this has some implications i don't fully understand yet, since I'm not sure if all functions check for the `-1` case

I made sure to do a global search with a few variations and the logs are the only place I found it doing the -1 check
As far as protocol goes, the KFO merger already did part of it, even IC messages can carry -1 charID now (treats it like a server message)

**Comment by oldmud0** [comment]
```
src/courtroom.cpp:1867:7: error: redefinition of 'objection_mod'

  int objection_mod = m_chatmessage[OBJECTION_MOD].toInt();

      ^

src/courtroom.cpp:1810:7: note: previous definition is here

  int objection_mod = m_chatmessage[OBJECTION_MOD].toInt(

      ^
```

**Pull request merged**
