### PR TITLE
Fix blankposting not respecting character ID's in the equation

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Fixes an issue where if you blankpost on top of another character's blankpost, your message won't show up on the ic log clientside.

### CODE REVIEW

**Review by oldmud0 — CHANGES_REQUESTED** [review]
`prev_char_id == f_char_id` will always be true

**Comment by Crystalwarrior** [comment]
> 
> 
> `prev_char_id == f_char_id` will always be true

Tested, it isn't because prev_char_id is set before the new m_chatmessage packet is parsed.

**Comment by oldmud0** [comment]
> the new m_chatmessage

oh that's right m_chatmessage is a `m`ember variable oh my gosh i hate this

**Review by oldmud0 — DISMISSED** [review]

**Comment by Crystalwarrior** [comment]
plEASE

**Review by in1tiate — DISMISSED** [review]

**Review by scatterflower — APPROVED** [review]
lgtm

**Review by oldmud0 — APPROVED** [review]
yuh

**Pull request merged**
