### PR TITLE
try this reviewer

### PR DESCRIPTION
**Pull request by stonedDiscord**

### CODE REVIEW

**Comment by stonedDiscord** [comment]
my code is perfect and the bot proves my point

**Comment by oldmud0** [comment]
Should disable

- cppcoreguidelines-pro-bounds-constant-array-index - Not relevant for qt
- cppcoreguidelines-owning-memory - Not relevant for qt
- cppcoreguidelines-init-variables - Too many false positives

Should also invoke clazy

**Comment by stonedDiscord** [comment]
it doesn't want to do clazy

**Comment by oldmud0** [comment]
Maybe you can find a github action that uses annotations instead of reviews? They look way nicer

**Review by oldmud0 — APPROVED** [review]
It's a start

**Pull request merged**
