### PR TITLE
Change the default theme to AceAttorney

### PR DESCRIPTION
**Pull request by stonedDiscord**

### CODE REVIEW

**Comment by Salanto** [comment]
Are you sure we should change it in client instead of just swapping the theme files in the theme repo?

**Comment by stonedDiscord** [comment]
I've considered it but it will mess with users who upgrade.
I'd prefer if the theme doesn't suddenly change for existing users who are on the default theme and like it.
This change will basically only affect users who don't have a ´config.ini´ yet (or deleted it)

**Comment by Salanto** [comment]
I just looked over the functions using default_theme are pathing related, so this might break if AceAttorney does not include all elements the default theme provides (like for effects). Otherwise yeah, it would be fine.

**Comment by stonedDiscord** [comment]
Yeah, I'll move the files over later today.

**Review by Salanto — APPROVED** [review]
No objections to a merge when the theme repo is updated.

**Comment by stonedDiscord** [comment]
https://github.com/AttorneyOnline/AO2-Themes/pull/20

**Comment by Salanto** [comment]
Just tested this, it will jack up the default theme either way since default contains few items, which will then be loaded from AceAttorney.

**Comment by Salanto** [comment]
LGTM

**Pull request merged**
