### PR TITLE
Add options to partially or fully disable the streaming functionality.

### PR DESCRIPTION
**Pull request by Salanto**
Because some people are in the outback with internet so bad we can't expect them to wait several seconds to load a file that may already be outdated by then. I'm pretty sure somebody who knows what they are doing will have a stroke reading this jank.

### CODE REVIEW

**Comment by oldmud0** [comment]
Is the load not async?

**Comment by Salanto** [comment]
The load blocks animations from playing in the viewport, which one may notice as a very minor hitch on a fast connection. On a very slow one, like 100kb/s it can freeze animations for several seconds. Tested with the latest version of BASS.

**Comment by oldmud0** [comment]
Okay, so it's not async. Can we make it async?

**Comment by Salanto** [comment]
Solving the right issue with the wrong approach. Closing PR to work on a better alternative.

**Pull request closed without merging**
