### PR TITLE
Make chat rate limit a setting in the options

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Increase default value from 200 to 300

### CODE REVIEW

**Review by in1tiate — APPROVED** [review]
seems legit

**Comment by stonedDiscord** [comment]
```
src/aooptionsdialog.cpp:231:49: error: no member named 'get_chat_ratelimit' in 'AOApplication'

  ui_chat_ratelimit_spinbox->setValue(p_ao_app->get_chat_ratelimit());

                                      ~~~~~~~~  ^

1 error generated.

make: *** [build/aooptionsdialog.o] Error 1```

**Review by oldmud0 — DISMISSED** [review]
compile error. bruh momento

**Review by stonedDiscord — APPROVED** [review]
works

**Review by in1tiate — APPROVED** [review]
lgtm

**Review by Iamgoofball — APPROVED** [review]

**Pull request merged**
