### PR TITLE
voranimation

### PR DESCRIPTION
**Pull request by stonedDiscord**
i probably could've written hamburger schnitzel and you wouldn't be able to tell

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
tfw is your pr name

**Comment by stonedDiscord** [comment]
ther german word for preanimation

**Review by oldmud0 — CHANGES_REQUESTED** [review]
Could you please do `lupdate` for deutsch

**Review by oldmud0 — APPROVED** [review]
Sorry I don't typically allow vore. But I'll allow "voranimation."

**Pull request merged**
