### PR TITLE
[Optional] Remove master server chat functions

### PR DESCRIPTION
**Pull request by Three-Dog-JLOAO**
Split PR of https://github.com/AttorneyOnline/AO2-Client/pull/354
Credits to whoever originally worked on this.

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
Master server chat may potentially have some use. Most themes still support it, and it's currently used to send important messages like a motd by @oldmud0. I'll let him weigh in if this should be considered tho

**Review by Crystalwarrior — CHANGES_REQUESTED** [review]
This approach will slightly break the me layouts, I dunno if simply removing existing functionality is worth anything no matter how niche it is.

**Comment by stonedDiscord** [comment]
this is a perfectly working feature

i vote no on removing it

**Comment by oldmud0** [comment]
Maybe remove the chat functionality itself but keep the MOTD window, but removal is not planned at the moment.

**Comment by Three-Dog-JLOAO** [comment]
@oldmud0 Just to clarify from what the pr does is removes the ability to type in the ms chat but still keeps the window to show the motd in the ms in the lobby, it also removes the entire ms chat and server/master button that switches between the master server chat and the ooc chat while retaining the ooc chat itself

**Comment by Three-Dog-JLOAO** [comment]
This is what it does:
ms chat
 The chat name and message windows are removed but the motd chat window is still maintained thanks to ui_chatbox in lobby.cpp

ooc chat

being as the ms chat in the court room is mostly never used by removing the ooc_toggle and ms_chatlog in courtroom.cpp it leaves the ooc chat present.

**Pull request closed without merging**
