### PR TITLE
Get old behavior if chat = default on char.ini

### PR DESCRIPTION
**Pull request by likeawindrammer**
Fix https://github.com/AttorneyOnline/AO2-Client/issues/229

### CODE REVIEW

**Comment by likeawindrammer** [comment]
> Essentially, you want the current theme to take precedence over `misc/default` when you say `default`.

This is what initiate and crystal wanted, but yeah, I'm not entirely convinced, maybe a keyboard like current_theme would be better instead of default for current theme.
Remembering more of what initiate said I now get that he was complaining about something more fundamental about how the client handle themes and the misc folder content. But that sounds like reviewing a considerable ammount of code and personally I don't want to do that for 2.8. I would rather leave the big changes, rewrites and other unfucking for 2.9. (which I can't wait to get started as soon as I finish making sure 2.8 will work well enough until 2.9 gets out)

**Comment by in1tiate** [comment]
I strongly disagree with this change. Many if not all servers have all of their characters' `chat` set, and this change would render the theme's ability to customize the chatbox effectively useless because in this _single instance_ the default theme overrides the user's theme. At least if `chat = default` paths to `misc/default` it's _consistent._ Pathing to the default theme is inconsistent behavior and generally confusing.

**Comment by Crystalwarrior** [comment]
Honestly I agree with @in1tiate, he raises a very good point. I would've stuck to my guns to keep treating misc/default as "yet another misc theme" but since a lot of people are running into issues as a result of this behavior maybe "default" should take it as a theme instead. Final decision up to @oldmud0

**Comment by scatterflower** [comment]
image

**Comment by oldmud0** [comment]
That screenshot has little context or rationale attached to it, so let me make my case here.

From my understanding, the value of `chat` used to correspond to the theme; thus, to use an AA chatbox, one would select the AA theme which would be `default`.

Due to changes, `misc/default` takes precedence over `themes/default` - which, for most users, makes little difference since `misc/default` also contains the AA chatbox.

The problem arises when a derivative chatbox wants to be made from the AA chatbox. This is actually an accidental feature because no theme other than `default` (which happens to be the AA theme) allows for derivative themes.

Unless `chat = default` is being used for an odd reason other than to reference the AA chatbox, the correct solution is to have these characters fixed. The ability for themes to override the `misc` folder is not a currently implemented feature.

**Pull request closed without merging**
