### PR TITLE
Remove dumb memes

### PR DESCRIPTION
**Pull request by in1tiate**
how did this make it into the merge

### CODE REVIEW

**Comment by in1tiate** [comment]
I'd rather not stop the button from appearing on failed login. I use the fact that doesn't happen to test the theme position of the guard button, and I know I'm not the only one who does that.

**Comment by Iamgoofball** [comment]
:-1: giving people a fake mod pass and laughing at this is great

**Comment by in1tiate** [comment]
"it's funny" is not a valid reason to add stupid behavior

**Comment by Iamgoofball** [comment]
Okay, then explain what's negatively detrimental about having a little easter egg in the repository? Because we aren't doing forks anymore, the whole point of the big client merger is so that we aren't all running different client and server versions and instead work collaboratively on a main branch.

Stopping the music is a legit concern, we could just move this to the modcall_player sfx.

**Comment by in1tiate** [comment]
Stopping the music is _exactly_ what's so detrimental. It's not cool for the music to just vanish into the ether when you typo your mod password. I'd be fine with using another player, this PR was made in ten seconds out of frustration.

**Comment by Iamgoofball** [comment]
Yeet, just edit this PR to make it use the modcall player and "./music/failed_login" and I'll merge it.

**Pull request merged**
