### PR TITLE
Refactor AOPacket

### PR DESCRIPTION
**Pull request by skyedeving**
## Unit Tests
https://github.com/skyedeving/AO2-Client/blob/fix-casedoc-loading-test/README_TEST.md
https://github.com/skyedeving/AO2-Client/blob/fix-casedoc-loading-test/test/test_aopacket.cpp

### CODE REVIEW

**Review by stonedDiscord — APPROVED** [review]
this is 200% more readable

**Review by oldmud0 — APPROVED** [review]
Though the whole network backend was refactored in ui-files, this is a nice refactor for the classic branch.

**Comment by oldmud0** [comment]
CI couldn't catch you error because it was on a remote branch.
```
src/aopacket.cpp:8:16: error: no matching constructor for initialization of 'QStringList'
  m_contents = QStringList(packet_contents.begin()+1, packet_contents.end()-1); // trims %
               ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by skyedeving** [comment]
Too cutting edge I suppose since constructor was added in 5.14

**Pull request merged**
