### PR TITLE
Fix sounds and blips being muted forever on changing character

### PR DESCRIPTION
**Pull request by in1tiate**
uncaught issue with #342

### CODE REVIEW

**Review by stonedDiscord — DISMISSED** [review]
it works

**Comment by oldmud0** [comment]
Wouldn't this just reintroduce #277?

**Comment by in1tiate** [comment]
> 
> 
> Wouldn't this just reintroduce #277? You're setting the volume before the client can receive confirmation that the character was successfully changed.

yes. fixed now

**Review by oldmud0 — APPROVED** [review]
Yep, looks like it's in the "appropriate" place now.

**Pull request merged**
