### PR TITLE
Slightly optimize area list, stop showing area index in ARUP

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Optimize area list slightly by recycling QTreeWidgetItems instead of clearing and creating them every time
Remove index that only shows up during ARUP cuz it confuses the hell out of area indexes defined by server

### CODE REVIEW

**Review by in1tiate — CHANGES_REQUESTED** [review]
If your "hub" hack breaks a client feature, the solution is not to remove the feature. Fix the indices.

**Comment by Crystalwarrior** [comment]
> If your "hub" hack breaks a client feature, the solution is not to remove the feature. Fix the indices.

The fix is on the server side by sending the indexes as part of the area name string, there's no other possible solution

**Comment by in1tiate** [comment]
> > If your "hub" hack breaks a client feature, the solution is not to remove the feature. Fix the indices.
> 
> The fix is on the server side by sending the indexes as part of the area name string, there's no other possible solution

In that case, server maintainers will need to be notified.

**Review by stonedDiscord — DISMISSED** [review]

**Comment by stonedDiscord** [comment]
how do i un-review a PR

**Comment by Salanto** [comment]
Is this relevant anymore?

**Review by in1tiate — APPROVED** [review]
This is whatever, it's a nothing burger. If it makes for less UI friction then go for it.

**Review by stonedDiscord — APPROVED** [review]
the area list still works and looks exactly the same

**Pull request merged**
