### PR TITLE
Fix or suppress compiler warnings (Qt 5.15 w/MinGW)

### LINKED ISSUE #799: QString::SplitBehavior is deprecated
https://doc.qt.io/qt-5/qstring-obsolete.html#SplitBehavior-enum

### PR DESCRIPTION
**Pull request by in1tiate**
Depends #812

Resolves #799, #800, and should allow us to go forward with #801 if I'm not mistaken

### CODE REVIEW

**Review by stonedDiscord — APPROVED** [review]
blessed

**Review by Salanto — APPROVED** [review]
Works as advertised.

**Comment by Salanto** [comment]
There is one issue, not MingW related, where MSVC is unable to parse the QMAKE flaf we put in the pro file. If that isn't needed anymore this would also work perfectly fine for both compilers.

**Comment by oldmud0** [comment]
You should run an interactive rebase and drop the screenshake related commits now that those have been merged.

**Comment by oldmud0** [comment]
squashed merge commit looks good actually.

**Pull request merged**
