### PR TITLE
Consolidate kick and kickban packets into one (more versatile) handler

### PR DESCRIPTION
**Pull request by in1tiate**
sister PR to https://github.com/AttorneyOnline/tsuserver3/pull/100

### CODE REVIEW

**Comment by oldmud0** [comment]
No more features allowed in 2.7-rc. Moved base to master. Wait for merge.

**Comment by stonedDiscord** [comment]
this is not a new feature but cleaning up

**Comment by oldmud0** [comment]
Well, now it's not a new feature anymore.

**Comment by in1tiate** [comment]
Marking as draft, I have some additional plans for this

**Comment by in1tiate** [comment]
Dead PR, closing.

**Pull request closed without merging**
