### PR TITLE
Allow button generator to generate both on and off buttons

### PR DESCRIPTION
**Pull request by in1tiate**

### CODE REVIEW

**Comment by oldmud0** [comment]
Doesn't make sense to me.

**Comment by in1tiate** [comment]
essentially right now we only check "is there an off button, and do we need an on button" before generating an "on" button. this adds the opposite check - "do we need an off button, and is there an on button" - to allow for generating buttons both ways

**Comment by oldmud0** [comment]
So if the on button is missing, it will darken the off button and call it an on button, and if the off button is missing, it will darken the on button and call it an off button.

**Comment by in1tiate** [comment]
It sounds confusing, but in practice it's more that it replaces whichever half of the buttons isn't there. It does this the moment you start playing as the character if the half it's replacing is _off, so it's fairly seamless.

**Comment by oldmud0** [comment]
The logic is not confusing. The result, however, is. Some characters will have all buttons dark except the one selected, and others will have all buttons light except the one selected.

**Comment by in1tiate** [comment]
This is already the case with some user-created buttons. There's not a standard way of doing it.

**Comment by oldmud0** [comment]
Ugh. Fine.

**Review by oldmud0 — APPROVED** [review]

**Review by Crystalwarrior — CHANGES_REQUESTED** [review]
Endorcing scuffed user practices by automatically generating it is much worse. I prefer phasing out the ass backwards way that exists with users, so I don't want this merged. They can still do it manually so nothing stops them, but if they want convenience they gotta submit to the way.

**Comment by in1tiate** [comment]
A possible alternative that preserves user choice is simply abolishing the _on _off system entirely. Have the users give us `button1`, we'll make a `button1_dark`, and we'll let the config decide whether `button1_dark` is used for "on" or "off"

**Comment by Crystalwarrior** [comment]
@in1tiate You know, that's a very sensible solution, sadly it would require abolishing backwards compatibility or renaming old-style buttons at runtime.

**Comment by in1tiate** [comment]
I still consider this useful, if servers want to reverse their buttons I don't see why one method should be enforced over the other by the client.

**Comment by oldmud0** [comment]
Since apparently my stupid self allowed this feature to slip in many moons ago, I'll merge this in to make sure that it's extra cursed.

**Review by oldmud0 — APPROVED** [review]

**Comment by Crystalwarrior** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by likeawindrammer** [comment]
https://discord.com/channels/278529040497770496/353369729328611330/856014535671676938
doesn't work at all

**Pull request merged**
