### PR TITLE
Add AppImage CI build

### PR DESCRIPTION
**Pull request by lambdcalculus**
What it says on the tin.

Requires #1003 so that paths in the AppImage are resolved correctly.

### CODE REVIEW

**Comment by TrickyLeifa** [comment]
The CI needs changed to be built against Ubuntu 22.04 rather than the latest as to ensure compatibility.

**Comment by Salanto** [comment]
After messing around I found two minor things :
The AppImage does not have an application icon and that its missing the execution bit on Linux, so people need to either chmod it or use the file property dialog. I think just adding the bit to the appimage before zipping should be enough to make it portable.
Otherwise works on anything never than 22.04 LTS (without updates) since it links to a GLibC that is not present on 20.04 LTS

**Comment by lambdcalculus** [comment]
Apparently the artifact clears the executable bit? This also seems to be happening to the dynamic build. Neither launch.sh nor the executable really come in as with x bit set, despite them being set in the CI.

**Comment by stonedDiscord** [comment]
The CI latest image has burnt us before with Mac
Can you be more specific about the version

**Comment by lambdcalculus** [comment]
I already set the Linux CI to `ubuntu-22.04`. I kept the formatting check on `ubuntu-latest`, since it doesn't really matter, so that might be what you saw.

**Comment by Salanto** [comment]
Any final objections here? @stonedDiscord @TrickyLeifa

**Comment by stonedDiscord** [comment]
Does the appimage work?

**Review by stonedDiscord — APPROVED** [review]

**Comment by lambdcalculus** [comment]
Works fine on my end. There are still some aspects that I can work out later, though, like how it doesn't seem to have an icon, or how `appimagetool` complains about a lack of update information when making the AppImage. But this is good for a start I think.

**Comment by Salanto** [comment]
Tested and the executable bit is set properly.

**Comment by lambdcalculus** [comment]
> The AppImage does not have an application icon

Ah, I should say, icons only work if you have [`appimaged`](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md) and configure it appropriately, I believe.

I think most desktop environments have a default icon for AppImages though. At least KDE does, from when I used it.

**Comment by stonedDiscord** [comment]
> Apparently the artifact clears the executable bit? This also seems to be happening to the dynamic build. Neither launch.sh nor the executable really come in as with x bit set, despite them being set in the CI.

zip files don't support the executable bit, you'd have to put it in a tar file before to keep the bit.

**Pull request merged**
