### PR TITLE
Switch to HTTP-based server list

### PR DESCRIPTION
**Pull request by oldmud0**
This PR implements the functionality set forth in #550. In summary:

- The server list has been moved to `https://servers.aceattorneyonline.com/servers`. Currently the bridge between the legacy MS and the new server list has not yet been set up.
- IPv6 is now supported. For dual-stack setups, you can also use a hostname when advertising your server.
- MOTD has been moved to `https://servers.aceattorneyonline.com/motd`.
- Version check has been moved to `https://servers.aceattorneyonline.com/version`.
- A privacy policy is now available in Settings > Privacy which is fetched from `https://servers.aceattorneyonline.com/privacy`. In the future, the privacy policy will vary by language.
- Added an option to opt-out of player count metrics in Settings > Privacy.

I am still wondering what to do with the master chat. I'm considering removing the entire widget from the courtroom, and removing the name and chat textboxes from the lobby.

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
fuck the master chat, the only thing it's useful for is /hdid and that's it lol

**Comment by stonedDiscord** [comment]
it was a nice feature but sadly a few individuals ruined it for everyone

maybe with better rate limiting we could allow it again?

**Comment by oldmud0** [comment]
It's basically obsoleted by Discord, so I changed the MS chat into a debug pane.
image

**Review by Crystalwarrior — APPROVED** [review]

**Review by Crystalwarrior — DISMISSED** [review]

**Review by Crystalwarrior — APPROVED** [review]
Code looks good but can you test if this works with the current server list just in case? Unless backwards compatibility is not necessary when the server list is switched out at the time of the update rolling out?

**Comment by oldmud0** [comment]
> Code looks good but can you set up legacy bridge before merge? Unless backwards compatibility is not necessary when the server list is switched out at the time of the update rolling out?

Already did, it's been running for two weeks now.

**Pull request merged**
